version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - "8081:8080"
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - red_web

  nginx_web:
    build:
      context: ./web
    container_name: nginx_web
    ports:
      - "8080:80"
    networks:
      - red_web

volumes:
  jenkins_home:

networks:
  red_web:
