version: '3.8'

services:
  web:
    build:
      context: ./web
    container_name: mi-web
    ports:
      - "8080:80"
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Jenkins puede usar Docker
    restart: always

volumes:
  jenkins_home:
